-- migrate:up

-- Generated by aggregating all order_lines across a finalized sale, grouped by
-- SKU. The team gets one bulk delivery, not individual buyer boxes.
CREATE TABLE pick_lists (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  campaign_id      uuid NOT NULL REFERENCES campaigns(id),
  pick_list_number text UNIQUE NOT NULL,
  status           text NOT NULL DEFAULT 'generated'
                   CHECK (status IN ('generated', 'in_progress', 'complete', 'cancelled')),
  assigned_to      uuid REFERENCES users(id),
  generated_at     timestamptz NOT NULL DEFAULT now(),
  completed_at     timestamptz,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  created_by       uuid REFERENCES users(id),
  deleted_at       timestamptz
);

CREATE TRIGGER pick_lists_set_updated_at
  BEFORE UPDATE ON pick_lists
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE pick_list_lines (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  pick_list_id      uuid NOT NULL REFERENCES pick_lists(id),
  sku_id            uuid NOT NULL REFERENCES skus(id),
  quantity_required integer NOT NULL,
  quantity_picked   integer NOT NULL DEFAULT 0,
  lot_id            uuid REFERENCES inventory_lots(id),
  picked_by         uuid REFERENCES users(id),
  picked_at         timestamptz,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  created_by        uuid REFERENCES users(id),
  deleted_at        timestamptz
);

CREATE INDEX idx_pick_list_lines_pick_list_id ON pick_list_lines(pick_list_id);

CREATE TRIGGER pick_list_lines_set_updated_at
  BEFORE UPDATE ON pick_list_lines
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- One bulk shipment to the team. Packing slip is rendered off this record
-- plus its pick list lines, not a separate table.
CREATE TABLE shipments (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  pick_list_id        uuid NOT NULL REFERENCES pick_lists(id),
  packing_slip_number text UNIQUE NOT NULL,
  carrier             text,
  tracking_number     text,
  shipped_at          timestamptz,
  delivered_at        timestamptz,
  delivery_signature  text,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  created_by          uuid REFERENCES users(id),
  deleted_at          timestamptz
);

CREATE TRIGGER shipments_set_updated_at
  BEFORE UPDATE ON shipments
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- migrate:down
DROP TABLE IF EXISTS shipments;
DROP TABLE IF EXISTS pick_list_lines;
DROP TABLE IF EXISTS pick_lists;
